"""Build js/image-meta.js from images/thumb:  slug: [width, height, averageColour]
Sizes let pages lay out paintings before the images load. The colour language
(accent, back-glow, room tint) is derived live in the browser, see Site.palette in js/site.js."""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent


def build():
    meta = {}
    for f in sorted((ROOT / "images" / "thumb").glob("*.jpg")):
        im = Image.open(f).convert("RGB")
        avg = im.resize((1, 1), Image.BOX).getpixel((0, 0))
        meta[f.stem] = [im.width, im.height, "#%02x%02x%02x" % avg]
    (ROOT / "js" / "image-meta.js").write_text(
        "// Generated by tools/palette.py - slug: [thumbWidth, thumbHeight, averageColour]\n"
        "window.IMAGE_META = " + json.dumps(meta, separators=(",", ":")) + ";\n", encoding="utf-8")
    return meta


if __name__ == "__main__":
    print(len(build()), "images")
